### ISSUE TITLE
Refactor Metadata Storage to Use Primitive Types for `starknet-rs` Agnosticism

### ISSUE THREAD

**Issue by remiroyc** [ArkProjectNFTs/ark-project#166]
**Is this feature related to a problem? Please describe.**

As highlighted by @glihm in [this discussion](https://github.com/ArkProjectNFTs/ark-project/pull/165#pullrequestreview-1710595715), the metadata storage trait (crates/ark-metadata/src/storage.rs) should be refactored. 

**Describe the solution you'd like**

Instead of using Starknet types, it should employ primitive types, ensuring complete agnosticism from starknet-rs.

**Comment by CristopherAguilar10** [comment]
Hello @remiroyc , can I work on this issue, it looks quite interesting and I would like to help?
