### ISSUE TITLE
Add cairo fmt to github CI

### ISSUE THREAD

**Issue by remiroyc** [ArkProjectNFTs/ark-project#191]
Add a github actions to format automatically the cairo codebase

**Comment by dbejarano820** [comment]
I can handle this

**Comment by dbejarano820** [comment]
There's already an action that checks for cairo code formatting
https://github.com/ArkProjectNFTs/ark-project/blob/main/.github/workflows/scarb.yml

Do you mean a pre-commit hook that formats it automatically?

**Comment by muheebyusufbaba1** [comment]
I would like to work on this
