### ISSUE TITLE
Support auction in the SDK

### ISSUE THREAD

**Issue by kwiss** [ArkProjectNFTs/ark-project#264]
## Is this feature related to a problem? Please describe.
Currently, our orderbook implementation supports auction orders. However, there is a limitation as the core and React SDK only support offer and listing types. This gap in functionality is a problem because it restricts our ability to fully utilize auctions in our system.

## Describe the solution you'd like
The ideal solution would be to extend support in both the core and React SDK to include auction types, alongside the existing offer and listing types. This would allow for a more comprehensive and functional integration of auction orders within our system.

## Alternative solutions
As an alternative, we could consider developing a separate module or plugin specifically for auction orders. However, this might lead to increased complexity and maintenance overhead, which is why integrating this functionality directly into the core and React SDK is preferred.

**Comment by princeibs** [comment]
Hi @kwiss, can I proceed with this?
