### ISSUE TITLE
Deployer fix: Update orderbook contract & starknet nft contract

### ISSUE THREAD

**Issue by kwiss** [ArkProjectNFTs/ark-project#275]
**Describe the bug**

We need to have the ability to update if the contract already exist the orderbook contract & starknet nft contract

**To Reproduce**

Deploy both contracts with the deployer

it also cause the CI to always deploy a new orderbook contract instead of updating it

**Comment by princeibs** [comment]
Hi @kwiss, if work has not commenced on this issue, I would like to proceed with it.

**Comment by kwiss** [comment]
Hey @princeibs sure, i think it's pretty easy to do, you just have to reproduce the logic in https://github.com/ArkProjectNFTs/ark-project/blob/main/packages/deployer/src/deployStarknetContracts.ts (deploy a new contract or update it if it doesn't exists)

here: https://github.com/ArkProjectNFTs/ark-project/blob/main/packages/deployer/src/deployArkchainContracts.ts 
& 
here: https://github.com/ArkProjectNFTs/ark-project/blob/main/packages/deployer/src/deployStarknetFreemintNft.ts

To work with this PR you have to make the whole thing locally you can follow this guide:
https://github.com/ArkProjectNFTs/ark-project/blob/main/packages/deployer/README.md#running--deploying-arkproject-locally

**Comment by princeibs** [comment]
It looks like something I can do @kwiss.
You can assign me to the task. Thanks

**Comment by kwiss** [comment]
good @princeibs do you need some help on it ? or some explanations ? we call do a call

**Comment by princeibs** [comment]
Hello @kwiss, just want to let you know that work is still in progress. I will create a PR once I am done

**Comment by princeibs** [comment]
> @princeibs dont hesitate to ask if you have any question.
Surely I won't. Thanks
