### ISSUE TITLE
Test React SDK

### ISSUE THREAD

**Issue by gershon** [ArkProjectNFTs/ark-project#428]
**Is this feature related to a problem? Please describe.**

React SDK is not tested.

**Describe the solution you'd like**

Write tests using [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/).

**Comment by ooochoche** [comment]
I’m available to work on this

**Comment by gershon** [comment]
Hi @od-hunter , go ahead, let me know if you need any assistance.

**Comment by gershon** [comment]
Hi @ooochoche, there will be other issues open for contribution in near future, thanks for offering!

**Comment by od-hunter** [comment]
Hello @gershon , so sorry I wouldn’t be able to do this anymore, @ooochoche can just go ahead. Decided to let you know on time. My apologies please.🙏🏼

**Comment by Joy-Adah** [comment]
Hi @gershon can I take this up?

**Comment by dhruvmalik007** [comment]
Hey @gershon ,

 i am handling this request in #451 , let me know if this has to be mock unit tests or workflow tests ? thanks

**Comment by gershon** [comment]
Hi @dhruvmalik007 , we are closing this issue as we are preparing a new release with SDK react test setup. There will be other issues listed for improving tests.

**Comment by dhruvmalik007** [comment]
ah well I had completed with the current one with list auctions and full fill auction. ok atleast keep the branch available so that i can improve the test .

**Comment by gershon** [comment]
@dhruvmalik007, thanks for your contributions! You can follow https://github.com/ArkProjectNFTs/ark-project/pull/440 for v2 updates, which should be released soon.
