### ISSUE TITLE
feat: build and export all ABIs

### ISSUE THREAD

**Issue by gershon** [ArkProjectNFTs/ark-project#466]
We should generate and export all contract ABIs to facilitate their usages and manipulations.

- ABIs should be generated during build
- ABIs should be defined and exported in constants

**Comment by ikemHood** [comment]
Would be happy to take on this by tomorrow 💫

**Comment by gershon** [comment]
Hi @ikemHood, let's go 🚀

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
hello, can i take on this? 

ETA within 24hrs

**Comment by Shoetan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hi, I'm Emmanuel and I'll be working on issue:

I estimate this will take 3 days to finish 
Basecamp graduate

### How I plan on tackling this issue
Here is how I would tackle this issue
Understand the scope of work better by asking questions.
Build contracts first
create a constants file for storing the ABI , Like abi-constant.cairo
Create a constant for each ABI.
Put ABI in constants like: const MY_CONTRACT_ABI: felt* = [
    // The ABI data goes here
];
Export the constants for use and manipulations.

**Comment by aji70** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
i'm a solidity and cairo smart contract  developer with over 2 years experience and belive i have the skill set for the task

**Comment by ScottyDavies** [comment]
hello @gershon i would love to take up this issue.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a Blockchain Dev

### How I plan on tackling this issue
I would take this steps in solving the issues:

- I will modify build process by integrating ABI generation in build tool
- I will Export ABIs as Constants 
- Utilize ABIs by importing and using ABIs in contract interactions
- Automate with Scripts 
- Documentation
- Write tests to validate contract interactions with ABIs.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
 have a solid background in blockchain development, specializing in writing and testing smart contracts using Solidity. I’ve worked on various decentralized applications (dApps), where I've built and deployed secure and efficient smart contracts on Ethereum. Additionally, I have experience in testing these contracts using frameworks like Hardhat and Truffle, ensuring they function as expected under different scenarios. My expertise in both Solidity development and rigorous testing practices will be valuable for this task.


### How I plan on tackling this issue
1. **Modify the Build Configuration:**
   - Update the build script (using tools like foundry) to include ABI generation. Ensure that the ABIs are automatically compiled each time contracts are built.

2. **Organize ABI Files:**
   - Create a dedicated directory (e.g., `/build/abis`) to store the generated ABI files for each contract, ensuring they are easily accessible.

3. **Create a Constants File:**
   - Create a `constants.js` (or equivalent) file that imports the generated ABIs from the ABI directory and exports them in a structured format (e.g., as an object with contract names as keys).

4. **Automate Exporting:**
   - Implement a script that runs post-build to dynamically gather and export all ABI files into the constants file, making the process seamless and reducing manual updates.

5. **Verify and Test Integration:**
   - Test the integration by importing the ABIs in various parts of the application to ensure they are functional and correctly interacting with the smart contracts.
   - Ensure proper error handling is in place to catch any issues related to ABI usage.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a skilled fullstack developer with a wealth of experience in both frontend and backend JavaScript as well as my knowledge of Rustlang, With a solid foundation in testing,I have mastered frameworks like Mocha, Chai, and Jest to ensure robust, reliable code in every project. In addition to traditional web development, I have a strong background in blockchain technology, with hands-on experience in Solidity for Ethereum-based smart contracts. Moreover, I have delved into the emerging world of StarkNet, working with Cairo, a cutting-edge language tailored for STARKs, making them a versatile developer capable of bridging both traditional and decentralized web applications.

### How I plan on tackling this issue
Having a background in blockchain development makes this easy as working with ABIs is an everyday thing, i will handle thecreating of abis on build, with well define exports

**Comment by ikemHood** [comment]
🚀
