### ISSUE TITLE
feat: add custom errors

### ISSUE THREAD

**Issue by gershon** [ArkProjectNFTs/ark-project#468]
Add and use sdk core custom errors to facilitate sdk usage and debug.

- errors should have a type (INVALID_START_AMOUNT, INVALID_END_DATE, ...)
- errors should have a message with context ("Invalid start date. Start date (${startDate}) cannot be in the past.", ...)
- errors should include a link to related docs (https://docs.arkproject.dev/)

**Comment by Iwueseiter** [comment]
Hi @gershon can I work on this?

**Comment by Jemiiah** [comment]
I would love to work on this issue @gershon here is my profile : https://app.onlydust.com/u/Jemiiah

**Comment by Kaminar-i** [comment]
hello @gershon please can i work on this issue tomorrow once the OD hack starts :)

**Comment by martinvibes** [comment]
hello @gershon please i would love to work on this issue tomorrow once the OD hack starts :)

**Comment by ShantelPeters** [comment]
Hi @gershon would be happy to take up this issue by tomorrow

**Comment by NueloSE** [comment]
@gershon  kindly assign me this task as i would like to make it my first contribution to this project.

**Comment by lordshashank** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hi, I have been contributing in odhacks for quite some time now and have expertise in rust and blockchain specs , few of them are 
- Contributed to Floresta as Summer of Bitcoin 2024 fellow
- contributed to RUst lang's codegen GCC and implemented new traits and tests.
- Contributed to starknet rust devnet in odhack

### How I plan on tackling this issue
I will integrate sdk core custom errorin sdk for better error handling and ease of debugging 
I will add error messages with proper context and links to debug them.

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a Web3/frontend developer 
With a lot of experiences in open source contribution.


### How I plan on tackling this issue
I will
1. Define Custom Errors: Create custom error types (e.g., INVALID_START_AMOUNT, INVALID_END_DATE) in the SDK core, using an enum to represent different error types. Include fields for error message, context, and a link to the docs.

2. Error Messages with Context: Implement detailed error messages that include relevant context (e.g., "Invalid start date. Start date (${startDate}) cannot be in the past.")

**Comment by aji70** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
i'm a solidity and cairo smart contract  developer with over 2 years experience and belive i have the skill set for the task

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
i am a frontend developer with experience using JS and TS for type safety

### How I plan on tackling this issue
I will start by defining the custom error types that I need to create, such as INVALID_START_AMOUNT, INVALID_END_DATE, etc. These error types will help categorize specific issues that may arise during SDK usage.
Create Error Messages:

For each error type, I will craft a meaningful error message that provides context. For example, I will create a message like "Invalid start date. Start date (${startDate}) cannot be in the past." This will give users a clear understanding of what went wrong.
Link to Documentation:

I will ensure that each error message includes a link to the relevant documentation (https://docs.arkproject.dev/) to assist users in troubleshooting and understanding the error better.
Implement Custom Errors:

I will implement these custom errors in the SDK core, making sure to use the appropriate syntax and structure as per the coding standards of the project. I will ensure that these errors are thrown at the correct instances where validation fails.
Test Error Handling:

After implementing the custom errors, I will write tests to validate that the errors are thrown correctly under the intended circumstances. This will help confirm that the error handling works as expected.
Update Documentation:

I will update any relevant documentation to include information about the new custom errors, their meanings, and how they can be resolved, ensuring that developers using the SDK have clear guidance.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I have experience in building SDKs and handling error management in various systems. I’ve implemented custom error handling in JavaScript/TypeScript projects, providing developers with clear error messages, types, and links to relevant documentation. This ensures a smooth debugging experience and improves SDK usability. My familiarity with tools like Next.js and TypeScript enables me to create a robust error-handling framework for this project.




### How I plan on tackling this issue
I would start by creating a custom error class that standardizes error types, messages, and links to documentation. This class would include parameters for the error type (e.g., `INVALID_START_AMOUNT`), a message that provides context (e.g., `Invalid start date. Start date (${startDate}) cannot be in the past.`), and a link to the related documentation for easy reference. I would then integrate these custom errors throughout the SDK, ensuring consistency and clarity for users. Finally, I would ensure that each error includes a link to the appropriate section in the documentation to facilitate troubleshooting.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged

hello i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor




### How I plan on tackling this issue
Have a type (e.g., INVALID_START_AMOUNT, INVALID_END_DATE).
Include a message with context (e.g., "Invalid start date. Start date (${startDate}) cannot be in the past.").
Provide a link to related documentation (e.g., https://docs.arkproject.dev/).

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
i am a blockchain developer with strong background in cario, typescript,javascript etc. i will love to work on this issue, kindly assign

### How I plan on tackling this issue
Implement custom SDK errors by defining error types such as INVALID_START_AMOUNT and INVALID_END_DATE, along with contextual messages like "Invalid start date. Start date (${startDate}) cannot be in the past." Each error should also include a link to the relevant documentation at https://docs.arkproject.dev/ to aid in debugging and enhance user experience.

**Comment by bhavyagosai** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hey, I am Bhavya, a seasoned frontend engineer with two years of professional experience. I have been working with react, react native, nextjs, typescript and javascript and have become very proficient in it.

### How I plan on tackling this issue
To approach the problem, we can create a custom error handling system that includes error types, context-specific messages, and documentation links.

Each error can include:

An errorType that describes the nature of the error.
A message that provides the specific context.
A documentationLink to guide developers to relevant sections in your docs.

This approach improves SDK usage by:

Providing meaningful error messages with context.
Guiding developers to the relevant part of the documentation.
Facilitating debugging with clear and categorized error types.

**Comment by ptisserand** [comment]
Hi @NueloSE any update on this?
ODHack end is quite near.

**Comment by NueloSE** [comment]
@ptisserand I'd need more context on 
- where am I defining the errors
- At what point in the SDK usage am I to throw those errors...

This would help me implement, use, and link it to the related docs.

**Kindly assist**

**Comment by gershon** [comment]
Hi @NueloSE, 
- you can define errors in `packages/core/src/errors`
- you can take inspiration from https://github.com/wevm/wagmi/tree/main/packages/core/src/errors
- you can use them by replacing existing errors, like in https://github.com/ArkProjectNFTs/ark-project/blob/feat/contract-v2/packages/core/src/actions/order/createOffer.ts#L67. 

You should create your contribution branch from `feat/contract-v2` as it contains latest changes to be released soon.

Lmk if you need more guidances or informations.

**Comment by NueloSE** [comment]
Thank you this makes more sense now, I will be making a pr b4 end of 2mrw

**Comment by NueloSE** [comment]
@gershon I made a PR and no review yet...

**Comment by gershon** [comment]
Hi @NueloSE, I'll review it shortly.

**Comment by ptisserand** [comment]
Closed by #480
